# Based on: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#using-mamba-install-or-pip-install-in-a-child-docker-image

# Start from a core stack version
FROM jupyter/datascience-notebook:9e63909e0317
